import './globals.css'
import Header from '../components/layout/header/header'
import Footer from '../components/layout/footer'
import { Inter } from 'next/font/google'
import { Fira_Mono } from 'next/font/google'


const fira = Fira_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--fira-mono'
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--inter'
});

export const metadata = {
  title: 'Portfolio - Maximiliano Maiz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fira.variable} ${inter.variable}`}>
        <Header />
        <main className="container mt-20 flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
